### ISSUE TITLE
Crashes with 40 megabyte profile

### ISSUE THREAD

**Issue by creikey** [colrdavidson/spall#20]
See attached file. Not sure why
[rpgpt.zip](https://github.com/colrdavidson/spall/files/10890439/rpgpt.zip)

**Comment by colrdavidson** [comment]
So, I've checked this out in the native version..
I *suspect* the web-version ran out of memory, trying to load your trace. The web version can only handle up to a fixed stack-depth, this bad boy is many thousands of levels deep.
![image](https://user-images.githubusercontent.com/6327402/224423325-460fca61-f446-4b0e-83a6-c5a029e3d139.png)

It looks like you forgot to add an end to `L1091 quad`
