### ISSUE TITLE
License inconsistency in spall.h vs LICENSE

### ISSUE THREAD

**Issue by dundarious** [colrdavidson/spall#21]
spall.h has `// SPDX-License-Identifier: 0BSD` but the repo LICENSE file is MIT.

The examples mostly do not have license info, so one might assume they fall under MIT by default.

Would be nice to more clearly specify things to be one license or the other, or at least resolve the ambiguity.

**Comment by colrdavidson** [comment]
Ah, yep. Thanks for the heads-up!
All of spall-web should fall under MIT, I've updated the license in spall.h to match.
